<?php
namespace App\Models;
use Illuminate\Database\Eloquent\Model;

class ApplicationPersonalLoanInformation extends Model {
	
    protected $fillable = [ 
        'app_id', 
        'reference_title', 
        'reference_full_name', 
        'reference_relation', 
        'reference_mobile_no', 
        'reference_home_telephone_no', 
        'reference_address', 
        'reference_po_box_no', 
        'existing_customer',
        'account_no',
        'cif_no',
        'about_your_business',
        'sole_proprietorship_vith_power_of_attorney',
        'sole_proprietorship_without_power_of_attorney',
        'free_zone_entity',
        'limited_liability_company',
        'other_please_specify',
        'years_in_business',
        'designation',
        'paid_up_capital',
        'no_of_employees',
        'ownership_details',
        //'percentage_ownership',
        'partner_name',
        'partner_ownership',
        'partner_nationality',
        'annual_bonus',
        'average_monthly_commission',
        'average_monthly_overtime',
        'spouse_fixed_monthly_income',
        'if_spouse_is_a_co_borrower',
        // 'spouse_reference_title',
        // 'spouse_reference_full_name',
        // 'spouse_reference_relation',
        // 'spouse_reference_mobile_no',
        // 'spouse_reference_home_telephone',
        // 'spouse_reference_address',
        // 'spouse_reference_po_box_no',
        'business_reference_company_name',
        'business_contact_person_name',
        'business_title',
        'business_designation',
        'business_relationship',
        'business_contact_number',
        'business_address',
        'business_emirate',
        'reference_1_title',
        'reference_1_name',
        'reference_1_relation',
        'reference_1_mobile_no',
        'reference_1_emirate',
        'reference_1_office_telephone',
        'reference_1_email',
        'reference_2_title',
        'reference_2_name',
        'reference_2_relation',
        'reference_2_mobile_no',
        'reference_2_emirate',
        'reference_2_office_telephone',
        'reference_2_email',
        'purpose_of_loan',
        'if_you_have_co_borrower',
        'co_borrower_title',
        'co_borrower_name',
        'relationship_to_primary_borrower',
        'co_borrower_signature',
        'co_borrower_date',
        'loan_amount',
        'interest_rate',
        'number_of_installments',
        'installment_start_date',
        'monthly_installment_amount',
        'processing_fee',
        'institution_name',
        'product_card_type',
        'account_card_number',
        'finance_amount',
        'monthly_installment',
        'outstanding_balance',
        'type_of_personal_finance',
        'investment_murabaha',
        'requested_financing_details',
        'customer_segment',
        'direct_debit_account_number',
        'other_bank_direct_debit_account_number',
        'other_bank_name',
        'frequency_of_payment',
        'type_of_new_account',
        'takaful',
        'receive_a_special_rate_to_participate',
        'ever_obtained_al_khair_financing',
        'details_bank_name',
        'details_branch',
        'details_account_since',
        'details_credit_bank',
        'details_credit_limit',
        'details_credit_account_since',
        'liabilities_bank_name',
        'liabilities_facility_type',
        'liabilities_monthly_installment_amount',
        'liabilities_outstanding_amount',
        'liabilities_other_bank_name',
        'liabilities_other_facility_type',
        'liabilities_other_monthly_installment_amount',
        'liabilities_other_outstanding_amount',
        'date_of_signing',
        'signature_of_applicant',
        'are_you_a_public_figure',
        'public_figure_position_title',
        'related_to_public_figure',
        'related_public_figure_position_title',
        'acknowledge_receiving_key_fact_statement',
        'hereby_give_our_consent_to_waive',
        'agree_bank_will_determine',
        'customer_name',
        'signature_date',
        'us_citizen_or_other',
        'town_or_city_of_birth',
        'country_of_birth',
        'individual_tax_cm_signature',
        'individual_tax_date',
        'promise_cm_name',
        'cost_price',
        'profit',
        'schedule_1_number_of_installments',
        'day_of_every_month',
        'murabaha_contract_or_proceeds_thereof',
        'schedule_2_emirates_islamic_bank',
        'schedule_2_date',
        'schedule_2_number_investment_certificates',
        'schedule_2_cost_price',
        'schedule_2_deferred_profit',
        'schedule_2_advance_payment',
        'schedule_2_murabaha_sale_price',
        'schedule_2_payment_date',
        'schedule_2_sale_date',
        'schedule_2_cut_off_time',
        'annexure_date',
        'annexure_ei_reference',
        'annexure_takaful_fees',
        'annexure_processing_fees',
        'annexure_trading_fees',
        'annexure_account_number',
        'annexure_collect_original_clearance',
        'annexure_post_settlement',
        'liability_from',
        'outgoing_bank_name',
        'salary_for_the_month',
        'debit_emi_account_no',
        'customer_undertaking_account_no',
        'created_at', 
        'updated_at' 
    ];

    public function store($inputs, $id = null)  {
        if ($id){
            return $this->find($id)->update($inputs);
        } else {
            return $this->create($inputs)->id;
        }
    }

}

 